### ISSUE TITLE
APC/template_APC_SmartConnect.yaml - type of host

### ISSUE THREAD

**Issue by pow3r77** [lestoilfante/zabbix-integrations#1]
Thank you for your job.
I'm try to setup, all ok, but what kind of HOST I have to create?
SNMP v2 and set my local address of the APC?

![image](https://github.com/lestoilfante/zabbix-integrations/assets/45035125/413b5bd6-0d3e-4c76-8b2a-bf2bd8310ed2)

**Comment by lestoilfante** [comment]
yes set IP to APC's local address. Internally template uses {HOST.IP} macro so either SNMP or Agent should be fine.
According to Zabbix doc this is how HOST.IP is resolved:
>In global scripts, interface IP/DNS fields and web scenarios the macro will resolve to the main agent interface, however, if it is not present, the main SNMP interface will be used. If SNMP is also not present, the main JMX interface will be used. If JMX is not present either, the main IPMI interface will be used.

**Comment by pow3r77** [comment]
Ok, I have do that, but the discovery can't find anything.
I have put the php script in the local proxy of Zabbix, If i try to use the script locally on the the proxy it works well and retrive correctly the info from the samrtconnect.
But zabbix can't find any item? Have you any suggestion?

![image](https://github.com/lestoilfante/zabbix-integrations/assets/45035125/ee5286ad-9927-48e0-91cb-de5ddea9c61b)

**Comment by lestoilfante** [comment]
No error shown on Info column?
![image](https://github.com/lestoilfante/zabbix-integrations/assets/4020261/25c58598-10a9-40e0-afb9-f346b3d19b98)

You might also want to check if your local `APC-ScrapConnect.php` file has `#!/usr/bin/php` at the top. Also, it may be stating the obvious, but the Zabbix Proxy must have execution rights on `APC-ScrapConnect.php`. Of course, this file must be located in the same path as defined in the Proxy configuration file under `ExternalScripts`

**Comment by pow3r77** [comment]
OK this is error:

![image](https://github.com/lestoilfante/zabbix-integrations/assets/45035125/274305d3-66d2-493d-8cea-1635410a8805)

**Comment by lestoilfante** [comment]
Looks like you need to fix file permissions
> ls -lh /usr/lib/zabbix/externalscripts/APC-ScrapConnect.php  

allow execution for user running your Zabbix server/proxy or just

> chmod +x /usr/lib/zabbix/externalscripts/APC-ScrapConnect.php

**Comment by pow3r77** [comment]
Thenk you for the support, now the error i changed:

![image](https://github.com/lestoilfante/zabbix-integrations/assets/45035125/dd401ea1-9439-4583-9e7d-7c923620d634)

**Comment by lestoilfante** [comment]
ok got it, increase [Server Timeout](https://www.zabbix.com/documentation/current/en/manual/appendix/config/zabbix_server#timeout) or [Proxy Timeout](https://www.zabbix.com/documentation/current/en/manual/appendix/config/zabbix_proxy#timeout) on .conf file.
Default is 3, use **30**.
Server/Proxy process needs to be restarted after config change

**Comment by pow3r77** [comment]
Perfect work like a charm!!

(in italiano... MITICO!!!) 

Grazie mille

**Comment by pow3r77** [comment]
Now I have all the item and trigger correctly poluated, not received yet teh value in "lastest data" but probably need time to do that

**Comment by pow3r77** [comment]
Confirm.... no data recevide. Only items and triggers created. No error
