### ISSUE TITLE
APC/template_APC_SmartConnect.yaml - Timeout settings

### ISSUE THREAD

**Issue by pow3r77** [lestoilfante/zabbix-integrations#2]
Good morning,
Yestarday I have setup correctly the template wiht the suggestion to increase the timeout on the .conf file.
in my dashboard I have few Bandiwdht monitoring that warks withuou any problem.
But if increase the timeout settings I have in all the Bandwith graph a "hole" of the monitoring for about 5/10 minute thath seems the zabbix can't read correctly the data form the Cisco interface. 
I have try to set the timeout at 3 seconds and the problem dissapear.
Have you any idea about this issue?

Thank you

**Comment by lestoilfante** [comment]
Hi, this has more to do with Zabbix conf and the way data is collected from Cisco.
I would start by looking at the Zabbix queue and logs.
My best bet would be related to poller number setup, but for all these topics is better to ask on Zabbix forum

**Comment by pow3r77** [comment]
OK thank you!
